### ISSUE TITLE
Script crashes if first VD is not zero.

### ISSUE THREAD

**Issue by psitem** [Orteko/megaclisas-status#2]
```
# python megaclisas-status.py
Traceback (most recent call last):
  File "megaclisas-status.py", line 295, in <module>
    data, good_arrays, bad_arrays, good_disks, bad_disks = get_raid_status()
  File "megaclisas-status.py", line 237, in get_raid_status
    array_details = get_array_info(controller_id, array_id)
  File "megaclisas-status.py", line 144, in get_array_info
    return (_id, raid_type, size, state, in_progress, cachecade_info)
UnboundLocalError: local variable 'raid_type' referenced before assignment
```

The initial cause is that get_array_info doesn't handle errors. Underlying that is the assumption that the LDs will run sequentially from 0 to ((megacli -LdGetNum -aN)  - 1). On my controller the first two LDs were removed so the count runs from 2 to ((megacli -LdGetNum -aN)  + 1).

```
# megacli -LdGetNum -a0

 Number of Virtual Drives Configured on Adapter 0: 11

Exit Code: 0x0b
```

```
# megacli -LDInfo -l0 -a0


Adapter 0 -- Virtual Drive Information:
Adapter 0: Virtual Drive 0 Does not Exist.

Exit Code: 0x01
```

```
# megacli -LDInfo -Lall -aAll -NoLog|grep 'Virtual Drive:'
Virtual Drive: 2 (Target Id: 2)
Virtual Drive: 3 (Target Id: 3)
Virtual Drive: 4 (Target Id: 4)
Virtual Drive: 5 (Target Id: 5)
Virtual Drive: 6 (Target Id: 6)
Virtual Drive: 7 (Target Id: 7)
Virtual Drive: 8 (Target Id: 8)
Virtual Drive: 9 (Target Id: 9)
Virtual Drive: 10 (Target Id: 10)
Virtual Drive: 11 (Target Id: 11)
Virtual Drive: 12 (Target Id: 12)
```

**Comment by Orteko** [comment]
In theory the latest commit should fix this.

Please test it out and report back (I don't currently have access to a server where I can reproduce this).

My fix still needs a little work to reduce some duplication on megacli commands however I think it should fix the immediate issue.

**Comment by tbyehl** [comment]
Awesome, I will take a look in the morning.

**Comment by tbyehl** [comment]
That did the trick for me. Thank you so much. 

```
# python megaclisas-status.py
-- Controller information --
-- ID | Model | Firmware
c0 | PERC H800 Adapter | 12.10.4-0001

-- Array information --
-- ID | Type | Size | Status | InProgress | CacheCade Info
c0u2 | RAID6 | 8185G | Optimal | None | Type : Read Only
c0u3 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u4 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u5 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u6 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u7 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u8 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u9 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u10 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u11 | RAID0 | 2728G | Optimal | None | Type : Read Only
c0u12 | RAID0 | 2728G | Optimal | None | Type : Read Only

-- Disk information --
-- ID | Model | Status
c0u2p0 | WD-WMC1T1585387WDC WD30EFRX-68AX9N0 80.00A80 | Online, Spun Up
c0u2p1 | WD-WMC1T1707161WDC WD30EFRX-68AX9N0 80.00A80 | Online, Spun Up
c0u2p2 | WD-WMC1T1526458WDC WD30EFRX-68AX9N0 80.00A80 | Online, Spun Up
c0u2p3 | WD-WMC1T1570366WDC WD30EFRX-68AX9N0 80.00A80 | Online, Spun Up
c0u2p4 | WD-WMC1T1052841WDC WD30EFRX-68AX9N0 80.00A80 | Online, Spun Up
c0u3p0 | 93C5K0ZIFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u4p0 | 93B3K0P6FTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u5p0 | 83SGK0WIFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u6p0 | 931FK0TCFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u7p0 | 83VCK17FFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u8p0 | 83U6K0BAFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u9p0 | 93B3K0QRFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u10p0 | 931FK0T9FTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u11p0 | 93C6K15WFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
c0u12p0 | 83VHK10AFTOSHIBA MG03ACA300 FL1A | Online, Spun Up
```

**Comment by Orteko** [comment]
No worries, thanks for the bug report :)
